# Generated by Django 4.0.5 on 2022-07-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_message_receipient_message_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='reciepient',
        ),
    ]
