# Generated by Django 4.0.5 on 2022-07-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_recipient_message_reciepient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciepient',
            new_name='recipient',
        ),
    ]
