# Generated by Django 4.0.5 on 2022-07-31 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['short_intro', 'created']},
        ),
    ]
